// lib/dummy-data/students.js
export const students = [
  {
    id: 1,
    first_name: 'Aarav',
    last_name: 'Reddy',
    college_code: 'VGN01',
    roll_no: '21VGNCSE001',
    college_name: 'Vignan Institute of Technology',
    year: '3rd Year',
    mobile: '9876543210',
    branch: 'CSE',
  },
  {
    id: 2,
    first_name: 'Sneha',
    last_name: 'Kumar',
    college_code: 'VGN02',
    roll_no: '21VGNITC012',
    college_name: 'Vignan Institute of Info Tech',
    year: '2nd Year',
    mobile: '9876501234',
    branch: 'IT',
  },
  {
    id: 3,
    first_name: 'Rahul',
    last_name: 'Sharma',
    college_code: 'VGN03',
    roll_no: '21VGNCSE003',
    college_name: 'Vignan University',
    year: '4th Year',
    mobile: '9876123456',
    branch: 'CSE',
  },
  {
    id: 4,
    first_name: 'Priya',
    last_name: 'Verma',
    college_code: 'VGN04',
    roll_no: '21VGNITC004',
    college_name: 'Vignan Women’s College',
    year: '1st Year',
    mobile: '9876987452',
    branch: 'IT',
  },
  {
    id: 5,
    first_name: 'Karan',
    last_name: 'Mehta',
    college_code: 'VGN05',
    roll_no: '21VGNITC005',
    college_name: 'Vignan Engineering College',
    year: '2nd Year',
    mobile: '9876234567',
    branch: 'ECE',
  },
  {
    id: 6,
    first_name: 'Anjali',
    last_name: 'Nair',
    college_code: 'VGN01',
    roll_no: '21VGNCSE006',
    college_name: 'Vignan Institute of Technology',
    year: '3rd Year',
    mobile: '9876001122',
    branch: 'CSE',
  },
  {
    id: 7,
    first_name: 'Aditya',
    last_name: 'Rao',
    college_code: 'VGN02',
    roll_no: '21VGNCSE007',
    college_name: 'Vignan Institute of Info Tech',
    year: '4th Year',
    mobile: '9876345678',
    branch: 'CSE',
  },
  {
    id: 8,
    first_name: 'Divya',
    last_name: 'Patel',
    college_code: 'VGN04',
    roll_no: '21VGNCSE008',
    college_name: 'Vignan Women’s College',
    year: '1st Year',
    mobile: '9876012345',
    branch: 'ECE',
  },
  {
    id: 9,
    first_name: 'Rohit',
    last_name: 'Mishra',
    college_code: 'VGN03',
    roll_no: '21VGNITC009',
    college_name: 'Vignan University',
    year: '2nd Year',
    mobile: '9876098765',
    branch: 'IT',
  },
  {
    id: 10,
    first_name: 'Meena',
    last_name: 'Desai',
    college_code: 'VGN05',
    roll_no: '21VGNCSE010',
    college_name: 'Vignan Engineering College',
    year: '3rd Year',
    mobile: '9876223344',
    branch: 'CSE',
  },
  {
    id: 11,
    first_name: 'Sanjay',
    last_name: 'Kapoor',
    college_code: 'VGN01',
    roll_no: '21VGNITC011',
    college_name: 'Vignan Institute of Technology',
    year: '4th Year',
    mobile: '9876554433',
    branch: 'IT',
  },
  {
    id: 12,
    first_name: 'Pooja',
    last_name: 'Singh',
    college_code: 'VGN02',
    roll_no: '21VGNITC012',
    college_name: 'Vignan Institute of Info Tech',
    year: '2nd Year',
    mobile: '9876009090',
    branch: 'IT',
  },
  {
    id: 13,
    first_name: 'Vikram',
    last_name: 'Yadav',
    college_code: 'VGN03',
    roll_no: '21VGNCSE013',
    college_name: 'Vignan University',
    year: '3rd Year',
    mobile: '9876888888',
    branch: 'CSE',
  },
  {
    id: 14,
    first_name: 'Neha',
    last_name: 'Joshi',
    college_code: 'VGN05',
    roll_no: '21VGNCSE014',
    college_name: 'Vignan Engineering College',
    year: '1st Year',
    mobile: '9876112233',
    branch: 'CSE',
  },
  {
    id: 15,
    first_name: 'Harsh',
    last_name: 'Malik',
    college_code: 'VGN04',
    roll_no: '21VGNITC015',
    college_name: 'Vignan Women’s College',
    year: '4th Year',
    mobile: '9876445566',
    branch: 'IT',
  },
  {
    id: 16,
    first_name: 'Shruti',
    last_name: 'Rana',
    college_code: 'VGN01',
    roll_no: '21VGNCSE016',
    college_name: 'Vignan Institute of Technology',
    year: '3rd Year',
    mobile: '9876778899',
    branch: 'CSE',
  },
  {
    id: 17,
    first_name: 'Arjun',
    last_name: 'Singhania',
    college_code: 'VGN02',
    roll_no: '21VGNITC017',
    college_name: 'Vignan Institute of Info Tech',
    year: '2nd Year',
    mobile: '9876888999',
    branch: 'IT',
  },
  {
    id: 18,
    first_name: 'Tanya',
    last_name: 'Gupta',
    college_code: 'VGN03',
    roll_no: '21VGNCSE018',
    college_name: 'Vignan University',
    year: '1st Year',
    mobile: '9876999000',
    branch: 'CSE',
  },
  {
    id: 19,
    first_name: 'Ishaan',
    last_name: 'Das',
    college_code: 'VGN05',
    roll_no: '21VGNCSE019',
    college_name: 'Vignan Engineering College',
    year: '4th Year',
    mobile: '9876000011',
    branch: 'CSE',
  },
  {
    id: 20,
    first_name: 'Kavya',
    last_name: 'Sen',
    college_code: 'VGN04',
    roll_no: '21VGNITC020',
    college_name: 'Vignan Women’s College',
    year: '3rd Year',
    mobile: '9876888777',
    branch: 'IT',
  },
  {
    id: 21,
    first_name: 'Dev',
    last_name: 'Chopra',
    college_code: 'VGN01',
    roll_no: '21VGNCSE021',
    college_name: 'Vignan Institute of Technology',
    year: '2nd Year',
    mobile: '9876001122',
    branch: 'CSE',
  },
  {
    id: 22,
    first_name: 'Riya',
    last_name: 'Agarwal',
    college_code: 'VGN02',
    roll_no: '21VGNCSE022',
    college_name: 'Vignan Institute of Info Tech',
    year: '1st Year',
    mobile: '9876002233',
    branch: 'CSE',
  },
  {
    id: 23,
    first_name: 'Amit',
    last_name: 'Chandra',
    college_code: 'VGN03',
    roll_no: '21VGNITC023',
    college_name: 'Vignan University',
    year: '3rd Year',
    mobile: '9876003344',
    branch: 'IT',
  },
  {
    id: 24,
    first_name: 'Swati',
    last_name: 'Jain',
    college_code: 'VGN05',
    roll_no: '21VGNITC024',
    college_name: 'Vignan Engineering College',
    year: '2nd Year',
    mobile: '9876004455',
    branch: 'IT',
  },
  {
    id: 25,
    first_name: 'Manav',
    last_name: 'Saxena',
    college_code: 'VGN04',
    roll_no: '21VGNCSE025',
    college_name: 'Vignan Women’s College',
    year: '4th Year',
    mobile: '9876005566',
    branch: 'CSE',
  },
];
